###


GET http://localhost/

###


GET http://localhost/event
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDQ2MTdkNjE3OTRhYTUyZGZhNGRlYyIsImlhdCI6MTY0ODgyNzMzMCwiZXhwIjoxNjQ4ODMwOTMwfQ.vMz4WcGZtsaeUvwIowDI7l1e74H2VGGbmBNBFmRJR14

###


GET http://localhost/event/624d86f8fafc904e75b4bae8
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDQ2MTdkNjE3OTRhYTUyZGZhNGRlYyIsImlhdCI6MTY0ODgyNzMzMCwiZXhwIjoxNjQ4ODMwOTMwfQ.vMz4WcGZtsaeUvwIowDI7l1e74H2VGGbmBNBFmRJR14

###


POST http://localhost/event
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDQ2MTdkNjE3OTRhYTUyZGZhNGRlYyIsImlhdCI6MTY0ODgyNzMzMCwiZXhwIjoxNjQ4ODMwOTMwfQ.vMz4WcGZtsaeUvwIowDI7l1e74H2VGGbmBNBFmRJR14
Content-Type: application/json

{
    "name" : "הדרכת חיתולים",
    "dateAndTime" : "2022-04-30T13:00Z",
    "place" : "בניין א' קומה 5 בחדר 435",
    "description" : "כולכם מוזמנים להדרכת חיתולים חגיגית"
}

###


GET http://localhost/tutorial

###


POST http://localhost/tutorial
Content-Type: application/json

{
    "hebrewURL" : "8ZlinO9JguE&t",
    "englishURL": "bG1yLTaxe6w&t"
}

###


GET http://localhost/information/

###


GET http://localhost/information/62614e7f03683570ad03e64e

###


POST http://localhost/information
Content-Type: application/json

{
    "title" : "מדוע פגים בוכים פחות",
    "text": "פגים בוכים פחות מתינוקות רגילים, זאת משום שאין להם את ההורמון שאחראי לבכי"
}

###


POST http://localhost/user/register
Content-Type: application/json

{
    "email" : "a@a.com",
    "password" : "12345",
    "fullName" : "מאור כספי",
    "israeliId" : "208460410",
    "phoneNumber" : "0547929879"
}

###


POST http://localhost/user/login
Content-Type: application/json

{
    "israeliId" : "208460410",
    "password" : "12345"
}

###


POST http://localhost/user/logout
Content-Type: application/json

{

}