###


GET http://localhost/

###


GET http://localhost/event
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDQ2MTdkNjE3OTRhYTUyZGZhNGRlYyIsImlhdCI6MTY0ODgyNzMzMCwiZXhwIjoxNjQ4ODMwOTMwfQ.vMz4WcGZtsaeUvwIowDI7l1e74H2VGGbmBNBFmRJR14

###


GET http://localhost/event/624b4e4b84559ed287217296
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDQ2MTdkNjE3OTRhYTUyZGZhNGRlYyIsImlhdCI6MTY0ODgyNzMzMCwiZXhwIjoxNjQ4ODMwOTMwfQ.vMz4WcGZtsaeUvwIowDI7l1e74H2VGGbmBNBFmRJR14

###


POST http://localhost/event
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDQ2MTdkNjE3OTRhYTUyZGZhNGRlYyIsImlhdCI6MTY0ODgyNzMzMCwiZXhwIjoxNjQ4ODMwOTMwfQ.vMz4WcGZtsaeUvwIowDI7l1e74H2VGGbmBNBFmRJR14
Content-Type: application/json

{
    "name" : "הדרכת חיתולים",
    "dateAndTime" : "12/05/2022 08:20",
    "place" : "בניין א' קומה 5 בחדר 435",
    "description" : "כולכם מוזמנים להדרכת חיתולים חגיגית!!"
}

###


POST http://localhost/auth/register
Content-Type: application/json

{
    "email" : "a@a.com",
    "password" : "12345"
}

###


POST http://localhost/auth/login
Content-Type: application/json

{
    "email" : "a@a.com",
    "password" : "12345"
}

###


POST http://localhost/auth/logout
Content-Type: application/json

{

}